language: emacs-lisp

env:
  matrix:
    - EMACS=emacs-snapshot

matrix:
  allow_failures:
    - env:
        - EMACS=emacs-snapshot

install:
  - if [ "$EMACS" = "emacs-snapshot" ]; then
        sudo add-apt-repository -y ppa:ubuntu-elisp/ppa &&
        sudo apt-get update -qq &&
        sudo apt-get install -qq emacs-snapshot &&
        sudo apt-get install -qq emacs-snapshot-el;
    fi

script:
  EMACS=$EMACS ./test-startup.sh

notifications:
  email: false

# Local Variables:
# indent-tabs-mode: nil
# coding: utf-8
# End: